name: Mirror to GitHub

on:
  push:
    branches:
      - main
      - master
      - '*'
    tags:
      - '*'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Mirror to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GH_MIRROR_TOKEN }}
        GITHUB_REPO: https://github.com/${{ secrets.GH_MIRROR_ACTOR }}/${{ secrets.GH_MIRROR_REPO }}
      run: |
        git config --global user.name "GitVerse Mirror"
        git config --global user.email "mirror@gitverse.local"
        
        # Удаляем старый remote если есть
        git remote remove github 2>/dev/null || true
        
        # Добавляем GitHub как remote
        git remote add github $GITHUB_REPO
        
        # Отправляем все ветки и теги
        git push --force github --all
        git push --force github --tags